version: '3.4'
services:
  jira:
    image: leloimr/jira:9.12.1
    container_name: jira-srv
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=4g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g'
    #depends_on:
    #  - mysql
    ports:
      - "8087:8080"
    volumes:
      - home_data:/var/jira
    restart: always
    networks:
      - jira

  #mysql:
  #  image: mysql:8.0
  #  container_name: mysql-jira
  #  environment:
  #    - TZ=Asia/Ho_Chi_Minh
  #    - MYSQL_DATABASE=jira
  #    - MYSQL_ROOT_PASSWORD=123456
  #    - MYSQL_USER=jira
  #    - MYSQL_PASSWORD=123123
  #  command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
#    ports:
#      - "13306:3306"
  #  volumes:
  #    - mysql_data:/var/lib/mysql
  #  restart: always
  #  networks:
  #    - network-bridge

  postgres:
    image: postgres:latest
    container_name: jira-postgressql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: 12345689
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - jira

networks:
  jira:
    driver: bridge

volumes:
  home_data:
    external: false
  #mysql_data:
  #  external: false
  postgres_data:
